In [1]:
import json
import os
import re
import threading
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(".env"))

GOOGLE_CLOUD_PROJECT = os.environ["GOOGLE_CLOUD_PROJECT"]
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION")
AGENT_ID = os.getenv("AGENT_ID")




PROJECT_NUMBER = os.getenv("PROJECT_NUMBER")
REASONING_ENGINE_ID = os.getenv("REASONING_ENGINE_ID")
# The deployed engine lives in us-west1, not in GOOGLE_CLOUD_LOCATION.
REASONING_ENGINE_LOCATION = os.getenv("REASONING_ENGINE_LOCATION", "us-west1")

import agentplatform
import google.auth
import google.auth.transport.requests
import pymupdf
from google.auth.transport.requests import AuthorizedSession

import requests

import pandas as pd
from io import StringIO

In [2]:
pdf_path = Path("invoices_for_test/fatura_bradesco-8.pdf")

with pymupdf.open(pdf_path) as document:
    page_texts = [page.get_text().strip() for page in document]

pdf_text = "\n".join(text for text in page_texts if text)
if not pdf_text:
    raise ValueError(f"No selectable text found in {pdf_path}; this PDF may need OCR.")

print(f"Extracted text from {len(page_texts)} pages ({len(pdf_text)} characters).")

Extracted text from 3 pages (13485 characters).

## Connect to the deployed Vertex AI agent

In [3]:
REASONING_ENGINE_NAME = (
    f"projects/{PROJECT_NUMBER}/locations/{REASONING_ENGINE_LOCATION}/"
    f"reasoningEngines/{REASONING_ENGINE_ID}"
)
USER_ID = "eduardo"

client = agentplatform.Client(project=GOOGLE_CLOUD_PROJECT, location=REASONING_ENGINE_LOCATION)
remote_agent = client.runtimes.get(name=REASONING_ENGINE_NAME)
credentials, _ = google.auth.default(
    scopes=["https://www.googleapis.com/auth/cloud-platform"]
)
authorized_session = AuthorizedSession(credentials)
REASONING_ENGINE_URL = (
    f"https://{REASONING_ENGINE_LOCATION}-aiplatform.googleapis.com/v1/{REASONING_ENGINE_NAME}"
)

print(f"Connected to deployed agent: {remote_agent.api_resource.name}")


def _warm_up_agent() -> None:
    try:
        authorized_session.post(
            f"{REASONING_ENGINE_URL}:streamQuery?alt=sse",
            json={
                "classMethod": "async_stream_query",
                "input": {"user_id": USER_ID, "message": "responda só: ok"},
            },
            timeout=(30, 120),
        ).close()
    except requests.RequestException as error:
        print(f"Warm-up failed (ignored): {error}")


# Wakes the engine in the background so the ~25s cold start overlaps with the next cells.
threading.Thread(target=_warm_up_agent, daemon=True).start()

Connected to deployed agent: projects/63660038188/locations/us-west1/reasoningEngines/4344676216691752960

In [4]:
class AgentRetryableError(RuntimeError):
    pass


RETRYABLE_ERROR_CODES = {"429", "500", "503", "_ResourceExhaustedError"}


def ask_agent(message: str, verbose: bool = False) -> str:
    response = authorized_session.post(
        f"{REASONING_ENGINE_URL}:streamQuery?alt=sse",
        json={
            "classMethod": "async_stream_query",
            "input": {"user_id": USER_ID, "message": message},
        },
        stream=True,
        timeout=(30, 600),
    )
    if not response.ok:
        error_class = (
            AgentRetryableError
            if str(response.status_code) in RETRYABLE_ERROR_CODES
            else RuntimeError
        )
        raise error_class(
            f"Agent query failed ({response.status_code}): {response.text}"
        )

    response_parts = []
    event_shapes = []
    try:
        for line in response.iter_lines(decode_unicode=True):
            if not line:
                continue
            if line.startswith("data:"):
                line = line[len("data:"):].strip()
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(event, dict):
                continue
            error_code = event.get("error_code") or event.get("code")
            if error_code:
                error_message = event.get("error_message") or event.get("message")
                error_class = (
                    AgentRetryableError
                    if str(error_code) in RETRYABLE_ERROR_CODES
                    else RuntimeError
                )
                raise error_class(f"Agent error {error_code}: {error_message}")
            content = event.get("content", {})
            parts = content.get("parts", []) if isinstance(content, dict) else []
            if len(event_shapes) < 5:
                event_shapes.append({
                    "keys": list(event.keys()),
                    "content_type": type(content).__name__,
                    "part_keys": [list(part.keys()) for part in parts if isinstance(part, dict)],
                })
            for part in parts:
                function_call = part.get("function_call")
                if function_call and verbose:
                    print(f"[agent tool call: {function_call.get('name')}]", flush=True)
                text = part.get("text")
                if text and not part.get("thought"):
                    if verbose:
                        print(text, end="", flush=True)
                    response_parts.append(text)
    finally:
        response.close()

    response_text = "\n".join(response_parts).strip()
    if not response_text:
        raise ValueError(f"No text content in stream; event shapes: {event_shapes}")
    return response_text


def ask_agent_with_retry(message: str, max_attempts: int = 4, verbose: bool = False) -> str:
    for attempt in range(1, max_attempts + 1):
        try:
            return ask_agent(message, verbose=verbose)
        except AgentRetryableError as error:
            if attempt == max_attempts:
                raise
            wait_seconds = 15 * 2 ** (attempt - 1)
            print(f"\n{error}\nRetrying in {wait_seconds}s (attempt {attempt + 1}/{max_attempts})...")
            time.sleep(wait_seconds)


def resposta_para_dataframe(resposta_agente: str) -> pd.DataFrame:
    bloco = re.search(
        r"```(?:json|csv)?\s*(.*?)```",
        resposta_agente,
        flags=re.IGNORECASE | re.DOTALL,
    )
    conteudo = (bloco.group(1) if bloco else resposta_agente).strip()

    if conteudo.startswith("{"):
        try:
            lancamentos = json.loads(conteudo)["lancamentos"]
        except (json.JSONDecodeError, KeyError, TypeError) as error:
            raise ValueError(
                f"Agent reply is not the expected JSON ({error}):\n{resposta_agente[:1000]}"
            ) from error
        return pd.DataFrame(lancamentos).rename(columns={"valor_pago": "valor pago"})

    # Fallback for agents still deployed with the CSV instructions.
    return pd.read_csv(StringIO(conteudo), sep=",")


def processar_com_agente_o_que_contas(
    conteudo_extrato: str,
    fluxo: str,
    verbose: bool = False,
) -> pd.DataFrame:
    prompt = (
        f"{fluxo}\n"
        "Não pesquise na web nem chame a busca do Google. "
        "Para estabelecimentos que você não reconhecer, use a categoria 'Outros'.\n\n"
        f"{conteudo_extrato}"
    )
    resposta_agente = ask_agent_with_retry(prompt, verbose=verbose)
    return resposta_para_dataframe(resposta_agente)

In [5]:
df_final = processar_com_agente_o_que_contas(
    conteudo_extrato=pdf_text,
    fluxo="fatura_bradesco",
)

df_final

,data,merchant,valor pago,categoria,pagamento,revisar
0,2026-09-25,CUSTO TRANS. EXTERIOR-IOF,0.95,Taxas e encargos,Bradesco,False
1,2026-08-27,Distribusion Luxor,873.38,Ônibus,Bradesco,False
2,2026-08-27,PAO DE ACUCAR-0001,116.41,Mercado,Bradesco,False
3,2026-08-27,PAO DE ACUCAR-0001,30.70,Mercado,Bradesco,False
4,2026-08-27,FARMAIS,19.87,Farmácia,Bradesco,True
5,2026-08-28,GRINDHOUSE UM POR CE,88.00,Outros,Bradesco,True
6,2026-08-28,MINUTO PA 1456,15.58,Mercado,Bradesco,True
7,2026-08-29,IFD*DE VERAS RESTAURANTE,68.99,Restaurante,Bradesco,False
8,2026-08-29,A2F SERVICOS DE ESTAC,20.00,Estacionamento,Bradesco,False
9,2026-08-29,PAO DE ACUCAR-0001,83.57,Mercado,Bradesco,False
10,2026-08-29,PAO DE ACUCAR-0001,132.79,Mercado,Bradesco,False
11,2026-08-29,CENOBEER LTDA,29.70,Restaurante,Bradesco,True
12,2026-08-30,INSALATA COMERCIO DE A,30.00,Restaurante,Bradesco,False
13,2026-08-30,Zupper *Zupper,546.51,Outros,Bradesco,True
14,2026-09-01,QUINTOANDAR,3512.52,Moradia,Bradesco,False
15,2026-09-01,PAO DE ACUCAR-0001,184.11,Mercado,Bradesco,False
16,2026-09-02,PAO DE ACUCAR-0001,87.49,Mercado,Bradesco,False
17,2026-09-04,PAO DE ACUCAR-0001,23.66,Mercado,Bradesco,False
18,2026-09-04,PAO DE ACUCAR-0001,25.98,Mercado,Bradesco,False
19,2026-09-04,PAO DE ACUCAR-0001,67.04,Mercado,Bradesco,False
20,2026-09-05,TONTONI,171.01,Restaurante,Bradesco,True
21,2026-09-05,INSALATA COMERCIO DE A,60.00,Restaurante,Bradesco,False
22,2026-09-05,PAO DE ACUCAR-0001,189.87,Mercado,Bradesco,False
23,2026-09-05,BOGO CAFE.,141.00,Restaurante,Bradesco,False
24,2026-09-06,MSF CAFE LTDA,38.42,Restaurante,Bradesco,True
25,2026-09-06,MARGHERITA PIZZERIA,149.50,Restaurante,Bradesco,True
26,2026-09-06,IkemenRamen,227.00,Restaurante,Bradesco,True
27,2026-09-06,NEWFIT COMERCIO DE ROUP,1099.00,Outros,Bradesco,True
28,2026-09-07,FISH MARKET PESCADOS E,304.70,Outros,Bradesco,True
29,2026-09-09,PAO DE ACUCAR-0001,329.95,Mercado,Bradesco,False
30,2026-09-10,PAO DE ACUCAR-0001,67.89,Mercado,Bradesco,False
31,2026-09-11,PAO DE ACUCAR-0001,328.84,Mercado,Bradesco,False
32,2026-09-11,PAO DE ACUCAR-0001,41.98,Mercado,Bradesco,False
33,2026-09-12,F PARKING JARDINS,50.00,Estacionamento,Bradesco,True
34,2026-09-12,GUSTO ITALIANO RESTAUR,500.02,Restaurante,Bradesco,True
35,2026-09-12,QUITO QUITO,311.88,Restaurante,Bradesco,False
36,2026-09-13,PAO DE ACUCAR-0001,5.06,Mercado,Bradesco,False
37,2026-09-13,Ingresse,1073.76,Lazer,Bradesco,True
38,2026-09-14,MP*VAIDEPROMO,1266.23,Outros,Bradesco,True
39,2026-09-14,LLDANUZIONET 01/12,23.27,Outros,Bradesco,True
40,2026-09-14,MEDIUM MONTHLY,27.20,Assinatura,Bradesco,False
41,2026-09-15,PB*WONDERLEV,129.60,Outros,Bradesco,False
42,2026-09-15,VAI DE PROMO*PROM,1204.77,Outros,Bradesco,True
43,2026-09-16,PAO DE ACUCAR-0001,68.13,Mercado,Bradesco,False
44,2026-09-17,PAO DE ACUCAR-0001,102.68,Mercado,Bradesco,False
45,2026-09-18,PAO DE ACUCAR-0001,84.02,Mercado,Bradesco,False
46,2026-09-19,IFD*DE VERAS RESTAURANTE,76.99,Restaurante,Bradesco,False
47,2026-09-19,PAO DE ACUCAR-0001,69.00,Mercado,Bradesco,False
48,2026-09-22,MP *ODPTECH,394.09,Ônibus,Bradesco,False
49,2026-09-24,ANUIDADE DIFERENCIADA 06/12,50.00,Taxas e encargos,Bradesco,False
50,2026-09-27,PADRE PAULO RICAR 12/12,55.90,Outros,Bradesco,True

## Validate against the invoice total

In [13]:
def extrair_total_fatura(texto: str) -> float | None:
    padroes = [
        r"Total da fatura em real\s+([\d.]+,\d{2})",
        r"Total da fatura\s+R\$\s*([\d.]+,\d{2})",
    ]
    for padrao in padroes:
        match = re.search(padrao, texto)
        if match:
            return float(match.group(1).replace(".", "").replace(",", "."))
    return None


def validar_total(
    df: pd.DataFrame,
    texto: str,
    coluna_valor: str = "valor pago",
) -> bool | None:
    total_fatura = extrair_total_fatura(texto)
    if total_fatura is None:
        print("Total da fatura não encontrado no texto; validação ignorada.")
        return None

    valores = pd.to_numeric(df[coluna_valor], errors="coerce")
    if valores.isna().any():
        print(f"Atenção: {valores.isna().sum()} linha(s) com '{coluna_valor}' não numérico.")
    soma = round(valores.sum(), 2)
    diferenca = round(soma - total_fatura, 2)
    if abs(diferenca) < 0.01:
        print(f"OK: soma das linhas ({soma:,.2f}) = total da fatura ({total_fatura:,.2f}), {len(df)} linhas.")
        return True
    print(
        f"MISMATCH: soma das linhas {soma:,.2f} vs total da fatura {total_fatura:,.2f} "
        f"(diferença {diferenca:+,.2f}), {len(df)} linhas."
    )
    return False


validar_total(df_final, pdf_text)

# Donations count toward the invoice total, so they are removed only after the check.
df_final = df_final[df_final["categoria"] != "Doação"].reset_index(drop=True)
df_final

OK: soma das linhas (14,599.01) = total da fatura (14,599.01), 51 linhas.

,data,merchant,valor pago,categoria,pagamento,revisar
0,2026-09-25,CUSTO TRANS. EXTERIOR-IOF,0.95,Taxas e encargos,Bradesco,False
1,2026-08-27,Distribusion Luxor,873.38,Ônibus,Bradesco,False
2,2026-08-27,PAO DE ACUCAR-0001,116.41,Mercado,Bradesco,False
3,2026-08-27,PAO DE ACUCAR-0001,30.70,Mercado,Bradesco,False
4,2026-08-27,FARMAIS,19.87,Farmácia,Bradesco,True
5,2026-08-28,GRINDHOUSE UM POR CE,88.00,Restaurante,Bradesco,True
6,2026-08-28,MINUTO PA 1456,15.58,Mercado,Bradesco,True
7,2026-08-29,IFD*DE VERAS RESTAURANTE,68.99,Restaurante,Bradesco,False
8,2026-08-29,A2F SERVICOS DE ESTAC,20.00,Estacionamento,Bradesco,False
9,2026-08-29,PAO DE ACUCAR-0001,83.57,Mercado,Bradesco,False
10,2026-08-29,PAO DE ACUCAR-0001,132.79,Mercado,Bradesco,False
11,2026-08-29,CENOBEER LTDA,29.70,Restaurante,Bradesco,True
12,2026-08-30,INSALATA COMERCIO DE A,30.00,Restaurante,Bradesco,False
13,2026-08-30,Zupper *Zupper,546.51,Avião,Bradesco,True
14,2026-09-01,QUINTOANDAR,3512.52,Moradia,Bradesco,False
15,2026-09-01,PAO DE ACUCAR-0001,184.11,Mercado,Bradesco,False
16,2026-09-02,PAO DE ACUCAR-0001,87.49,Mercado,Bradesco,False
17,2026-09-04,PAO DE ACUCAR-0001,23.66,Mercado,Bradesco,False
18,2026-09-04,PAO DE ACUCAR-0001,25.98,Mercado,Bradesco,False
19,2026-09-04,PAO DE ACUCAR-0001,67.04,Mercado,Bradesco,False
20,2026-09-05,TONTONI,171.01,Restaurante,Bradesco,True
21,2026-09-05,INSALATA COMERCIO DE A,60.00,Restaurante,Bradesco,False
22,2026-09-05,PAO DE ACUCAR-0001,189.87,Mercado,Bradesco,False
23,2026-09-05,BOGO CAFE.,141.00,Restaurante,Bradesco,True
24,2026-09-06,MSF CAFE LTDA,38.42,Restaurante,Bradesco,True
25,2026-09-06,MARGHERITA PIZZERIA,149.50,Restaurante,Bradesco,True
26,2026-09-06,IkemenRamen,227.00,Restaurante,Bradesco,True
27,2026-09-06,NEWFIT COMERCIO DE ROUP,1099.00,Outros,Bradesco,True
28,2026-09-07,FISH MARKET PESCADOS E,304.70,Mercado,Bradesco,True
29,2026-09-09,PAO DE ACUCAR-0001,329.95,Mercado,Bradesco,False
30,2026-09-10,PAO DE ACUCAR-0001,67.89,Mercado,Bradesco,False
31,2026-09-11,PAO DE ACUCAR-0001,328.84,Mercado,Bradesco,False
32,2026-09-11,PAO DE ACUCAR-0001,41.98,Mercado,Bradesco,False
33,2026-09-12,F PARKING JARDINS,50.00,Estacionamento,Bradesco,True
34,2026-09-12,GUSTO ITALIANO RESTAUR,500.02,Restaurante,Bradesco,True
35,2026-09-12,QUITO QUITO,311.88,Restaurante,Bradesco,False
36,2026-09-13,PAO DE ACUCAR-0001,5.06,Mercado,Bradesco,False
37,2026-09-13,Ingresse,1073.76,Lazer,Bradesco,True
38,2026-09-14,MP*VAIDEPROMO,1266.23,Outros,Bradesco,True
39,2026-09-14,LLDANUZIONET 01/12,23.27,Outros,Bradesco,True
40,2026-09-14,MEDIUM MONTHLY,27.20,Assinatura,Bradesco,False
41,2026-09-15,PB*WONDERLEV,129.60,Outros,Bradesco,False
42,2026-09-15,VAI DE PROMO*PROM,1204.77,Outros,Bradesco,True
43,2026-09-16,PAO DE ACUCAR-0001,68.13,Mercado,Bradesco,False
44,2026-09-17,PAO DE ACUCAR-0001,102.68,Mercado,Bradesco,False
45,2026-09-18,PAO DE ACUCAR-0001,84.02,Mercado,Bradesco,False
46,2026-09-19,IFD*DE VERAS RESTAURANTE,76.99,Restaurante,Bradesco,False
47,2026-09-19,PAO DE ACUCAR-0001,69.00,Mercado,Bradesco,False
48,2026-09-22,MP *ODPTECH,394.09,Ônibus,Bradesco,False
49,2026-09-24,ANUIDADE DIFERENCIADA 06/12,50.00,Taxas e encargos,Bradesco,False
50,2026-09-27,PADRE PAULO RICAR 12/12,55.90,Outros,Bradesco,True